"""Add Garden recommendatino stuff to model

Revision ID: 1fe4ef7d3499
Revises: 0b1eadd_garden_recommendations
Create Date: 2025-08-08 00:36:25.412282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe4ef7d3499'
down_revision: Union[str, None] = '0b1eadd_garden_recommendations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
