"""New models ellipse, notes etc

Revision ID: 91f5c74ba012
Revises: 767df6e8c2a2
Create Date: 2025-08-07 23:01:52.238861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f5c74ba012'
down_revision: Union[str, None] = '767df6e8c2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden_elements', sa.Column('shape', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garden_elements', 'shape')
    # ### end Alembic commands ###
