"""Create gardens and garden_elements tables

Revision ID: f5d02822f6e6
Revises: 28d9b4ed5005
Create Date: 2025-08-03 19:25:21.775557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d02822f6e6'
down_revision: Union[str, None] = '28d9b4ed5005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
